Support syntax of global variables
kornilova203/matlab-IntelliJ-plugin pull request #47
Opened 2019-02-27 21:29 UTC by fernandreu

Hi,

I attempted to implement issue #32, while adding test files for it and ensuring syntax highlighting works. I am completely new to lexers and IntelliJ plugins, so feel free to modify / reject this!

While doing this, I have seen that lines such as "global a if b == 2 c = 3 end" do not flag any errors, but I think they should. However, I saw that the same occurs with other keywords, such as "try if b == 2 c = 3 end end". Hence, if this is actually an issue, hopefully it is not directly concerning the global keywords.

Finally, MATLAB would also highlight the global variables in a different color, both when you declare them as global and later every time they are used. Should this behaviour be implemented here as well? I have not checked how this could be done, but I suspect it will have less to do with updating the lexer and more to do with the Kotlin classes.

2019-02-27 21:35 UTC, kornilova-l commented
That’s awesome! I’ll review it tomorrow :)

2019-02-28 11:30 UTC, kornilova203 requested changes
Looks good!
Only couple of small changes required

2019-02-28 11:30 UTC, kornilova-l commented on grammar/Matlab.bnf
> +global_block ::= global br* IDENTIFIER (br* IDENTIFIER)* [',' | sep] { pin=1 }
Let's rename the rule to `global_variable_declaration`
Also you do not need `[',' | sep]` at the end because this suffix is in `element` rule

2019-02-28 11:30 UTC, kornilova-l commented on testData/parser/GlobalVariables.txt
> +    PsiElement(NEWLINE)('\n')
Seems like tests should trim extra whitespaces in test data
When I run the test I see that there is no last line `PsiElement(NEWLINE)('\n')`, so just remove it (and re-run test to check that it works)

2019-02-28 11:35 UTC, kornilova-l commented on grammar/Matlab.bnf
> +global_block ::= global br* IDENTIFIER (br* IDENTIFIER)* [',' | sep] { pin=1 }
I think `global_variable_declarations` would be better ('s' on the end)

2019-02-28 11:52 UTC, kornilova-l commented
"try if b == 2 c = 3 end end" is valid octave statement. Does it cause error in Matlab?

2019-02-28 11:54 UTC, kornilova-l commented
We can add color to global variables
But we need to resolve them, it's should not be difficult. I created the issue about it #48 you may try to implement it
Note that currently resolve works only within one file (see #24)

2019-02-28 19:56 UTC, fernandreu commented
Thanks for the feedback! I will try to make all those changes today / tomorrow.

> "try if b == 2 c = 3 end end" is valid octave statement. Does it cause error in Matlab?

In MATLAB (R2018b at least) I obtain this:
![matlab error](https://user-images.githubusercontent.com/2480661/53594158-2693df80-3b92-11e9-9fd3-b0d07fb91af3.png)
(`c` has just a warning, and the error on the `try` simply says "Code analysis did not complete. File contains too many syntax errors.")

Anyway, I guess it is good as it is now if Octave is fine with it.

Once I am done, I will also have a look at #48 and see if I can implement it.

2019-03-01 09:03 UTC, kornilova203 approved these changes

2019-03-01 09:03 UTC, merged