Add type info action
kornilova203/matlab-IntelliJ-plugin pull request #92
Opened 2020-08-30 18:33 UTC by YaPravaATyNet

2020-08-31 12:38 UTC, kornilova203 requested changes
I would add an interface e.g. `MatabTypedExpr` and add mixins for different expressions that will implement this interface. E.g. one mixin for binary expressions, one mixin for literal expression.
Then you'll be able to show type info for all expressions not only references.

2020-08-31 12:38 UTC, kornilova203 commented on src/com/github/kornilova203/matlab/psi/types/typeUtil.kt
> +}
It's better to use `MatlabClassDeclarationImpl.getName` method instead of searching for identifier

2020-08-31 12:38 UTC, kornilova203 commented on src/com/github/kornilova203/matlab/psi/types/typeUtil.kt
> +}
This can be moved to binary expression class. Maybe create a mixin for it?

2020-08-31 12:38 UTC, kornilova203 commented on src/com/github/kornilova203/matlab/MatlabTypeProvider.kt
> +                .filter(MatlabRefExpr::class.java)
You are able to get type of all expressions not only reference expressions

2020-08-31 14:26 UTC, YaPravaATyNet commented
Ok, I thought about mixins and get type for all expressions (not only for references), but I don't know, how can I cash in this case because ResolveCashe is only for references

2020-09-03 14:21 UTC, kornilova203 commented
Probably it's okay not to cache types of these elements

2020-09-03 14:26 UTC, merged